@extends('user.layouts.front')

@section('styles')

<style>
    .terms-section {
            background-color: #f4f4f4;
            text-align: center;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            margin-bottom: 40px;
        }
        .terms-section h1 {
            font-size: 2.8rem;
            font-weight: 700;
            color: #333;
            margin-bottom: 20px;
            text-transform: uppercase;
        }
        .terms-section h2 {
            font-size: 2rem;
            color: #444;
            font-weight: 600;
            margin-top: 30px;
            margin-bottom: 15px;
        }
        .terms-section p {
            font-size: 1.2rem;
            line-height: 1.8;
            color: #555;
            text-align: justify;
            margin-bottom: 20px;
        }
        
        .cta-note {
            background-color: #f0f8ff;
            color: #2a3d56;
            border-radius: 5px;
            font-size: 1.1rem;
            margin-top: 40px;
            text-align: center;
        }
        .cta-note a {
            color: #2a3d56;
            text-decoration: underline;
        }
</style>
@endsection

@section('content')


<section class="pt-40 pb-40 search-bg-pooja">
    <div class="container">
        <div class="row">
            <div class="contents-wrapper">
                <div class="sc-gJqsIT bdDCMj logo" height="6rem" width="30rem">
                    <div class="low-res-container">
                    </div>
                </div>
                <h1 class="sc-7kepeu-0 kYnyFA description">Term and condition</h1>
               
            </div>
        </div>
</section>

<section class="pt-40 pb-40">
    <div class="container">
        <section class="pt-40 pb-40">
            <div class="container">
                <h2>Introduction</h2>
                <p>
                    This document is an electronic record in terms of the Information Technology Act, 2000 (“IT Act, 2000”), the applicable rules thereunder and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
                
                <h2>Acceptance of Terms</h2>
                <p>
                    This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access to or usage of www.33crores.com website.
                </p>
                
                <h2>Platform Ownership</h2>
                <p>
                    The domain name www.33crores.com, including the related mobile site and mobile application as well as the seller portal (hereinafter referred to as “Platform”) is owned and operated by www.33crores.com (hereinafter referred to as 'www.33crores.com'), a company with its registered office at No 68, Sector 5, Niladrivihar, Chandrasekharpur, Bhubaneswar - 751021, Odisha, India.
                </p>
                
                <h2>Definitions</h2>
                <p>
                    For the purpose of the Terms of Use (hereinafter referred to as “ToU”), wherever the context so requires, ‘you’ and ‘your’ shall relate to any natural or legal person who has agreed to become a seller on the Platform by providing registration data while registering on the Platform using computer systems. The word ‘user’ shall collectively imply a seller, a buyer, and any visitor on the Platform, and the terms ‘we’, ‘us’ and ‘our’ shall mean www.33crores.com.
                </p>
                
                <h2>Agreement to Terms</h2>
                <p>
                    Your use of the Platform and the features therein is governed by the following terms and conditions (ToU) including applicable policies available on the Platform, notifications, and communications sent to you on the Platform which are incorporated herein by way of reference. By mere use of the Platform, you shall be contracting with www.33crores.com, and these terms and conditions including the policies constitute your binding obligations to www.33crores.com.
                </p>
                
                <h2>Modification of Terms</h2>
                <p>
                    We reserve the right, at our sole discretion, to change, modify, add, or remove portions of the ToU at any time. We will notify you through any of the communication modes as mentioned in this ToU in case of any changes or updates to the ToU that materially impact your use of the Platform. Your continued use of the Platform following the changes or updates will mean that you accept and agree to the revisions.
                </p>
                
                <h2>Access and Use of Platform</h2>
                <p>
                    Accessing, browsing, or otherwise using the Platform indicates your agreement with all the terms and conditions under the ToU. Please read the ToU carefully before proceeding. By impliedly or expressly accepting the ToU, you also accept and agree to be bound by all of www.33crores.com's policies applicable to you, as amended, from time to time.
                </p>
        
                <div class="cta-note">
                    By using this website, you acknowledge and agree to the terms outlined in this Terms of Use document.
                </div>
            </div>
        </section>

@endsection

@section('scripts')
@endsection